# Generated by Django 5.1.2 on 2024-10-29 14:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Введите место', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время выполнения', verbose_name='Время')),
                ('action', models.CharField(help_text='Введите действие', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Это приятная привычка?', verbose_name='Приятная привычка?')),
                ('reward', models.CharField(blank=True, help_text='Если не указана связанная привычка, укажите вознаграждение', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('frequency', models.IntegerField(default=1, help_text='Укажите периодичность (1 ежедневно)', verbose_name='Периодичность')),
                ('estimated_time', models.DurationField(default=datetime.timedelta(seconds=120), help_text='Сколько будет длиться выполнение', verbose_name='Продолжительность')),
                ('is_public', models.BooleanField(default=False)),
                ('related_habit', models.ForeignKey(blank=True, help_text='Если это полезная привычка, укажите вознаграждение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
