# Generated by Django 5.1.2 on 2024-11-01 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Когда отправлено напоминание', verbose_name='Время отправки')),
                ('delivery_status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Не отправлено')], help_text='Статус отправки напоминания', max_length=20, verbose_name='Статус доставки')),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке, если отправка не удалась', null=True, verbose_name='Сообщение об ошибке')),
                ('habit', models.ForeignKey(help_text='Привычка, к которой относится напоминание', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_histories', to='habits.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'История напоминаний',
                'verbose_name_plural': 'Истории напоминаний',
            },
        ),
    ]
